config/routes.rb
Champax::Application.routes.draw do

  namespace :admin do
    root :to => 'coupons#index'
    resources :businesses
    resources :categories 
    resources :coupons
    resources :settings, :only => [:index]
    match '/settings/set_ads', :to => 'settings#set_ads', :as => :settings_set_ads
    resources :ads
    resources :sessions, :only => [:new, :create, :destroy]
    resources :admin_user, :only => [:edit, :update]
    
    match '/login', :to => 'sessions#new'
    match '/logout', :to => 'sessions#destroy'
  end
  
  match "/c/:id/" => 'views#tweet_link'
  match "/New-Coupons" => 'views#by_new', :as => :coupons_by_new 
  match "/Hot-Coupons" => 'views#by_hot', :as => :coupons_by_hot 
  match "/Online-Only-Coupons" => 'views#by_online_only', :as => :coupons_by_online_only
  match "/Search-Coupons" => 'views#search'
  match "/Contact" => 'pages#contact', :as => :contact
  match "/Help" => 'pages#help', :as => :help
  match "/Help/Disable-Popups" => 'pages#help_popups', :as => :help_popup
  match "/About" => 'pages#about', :as => :about
  match "/For-Businesses" => 'pages#for_businesses', :as => :for_businesses 
  match "/For-Businesses/Why-Coupons" => 'pages#why_coupons', :as => :why_coupons 
  match "/print/:id" => 'views#print_coupon'
  match "/ajax/rate_coupon/:id", :to => "views#rate_coupon", :as => :rate_coupon
  match "/:name/c" => 'views#by_category'
  match "/:name/t" => 'views#by_town'
  match "/:name/d" => 'views#by_distance'
  match "/:business_name/:short_description/:id" => 'views#coupon', :constraints => { :short_description => /.*/ }
  
  
  root :to => 'pages#home'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  
  def self.getSetting(key)
    setting = Setting.where("key = ?", key).first()
    if setting 
      return setting.value
    else 
      return ""
    end
  end
  
  def self.setSetting(key, value)
    setting = Setting.find_or_create_by_key(key)
    setting.value = value
    setting.save
  end 
  
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController
  before_filter :authenticate
  
  def index 
    @title = "Settings"
    @skyscraper_left = Ad.find_by_id(Setting::getSetting('skyscraper_left'))
    @skyscraper_right = Ad.find_by_id(Setting::getSetting('skyscraper_right'))
  end
  
  def set_ads
    Setting.setSetting('skyscraper_left', params[:skyscraper_left])
    Setting.setSetting('skyscraper_right', params[:skyscraper_right])
    flash[:success] = "Site Ads Updated."
    redirect_to admin_settings_path
  end
  

end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
  
  def banner_select(type, default)
    ads = Ad.where('banner_type = ?', type).order('name').collect { |a| [a.name, a.id] }.insert(0,"")
    options_for_select(ads, default)
  end
  
end

app/views/admin/settings/index.html.erb
<% content_for :side_menu do %>
  <div id="admin_side_menu">
    <%= button_to 'Add New Banner Ad', new_admin_ad_path, :method => :get, :class => 'lg_button' %>
    <br/><br/>
    <%= button_to 'Edit Banner Ads', admin_ads_path, :method => :get, :class => 'lg_button' %>
  </div>
<% end %>

<div class="title"><%= @title %></div>

<div class="subtitle">Site Ads</div>
<%= form_tag admin_settings_set_ads_path, :class=>'admin_form' %>
<div class='two_column'>
  <div class="field">
    <label>Current Left Skyscraper</label>
    <% if @skyscraper_left && @skyscraper_left.image.exists? %>  
      <%= image_tag @skyscraper_left.image.url, :size => '160x600' %>
    <% else %>
      <div class="not_found">No Image Set</div>
    <% end %>
  </div>
  <div class="field">
    <label>Set Left Skyscraper</label>
    <%= select_tag(:skyscraper_left, banner_select('wide_skyscraper', (@skyscraper_left ? @skyscraper_left.id : '')), :class => 'short_field') %>
  </div>
</div>

<div class='two_column'>
  <div class="field">
    <label>Current Right Skyscraper</label>
    <% if @skyscraper_right && @skyscraper_right.image.exists? %>  
      <%= image_tag @skyscraper_right.image.url, :size => '160x600' %>
    <% else %>
      <div class="not_found">No Image Set</div>
    <% end %>
  </div>
  <div class="field">
    <label>Set Right Skyscraper</label>
    <%= select_tag(:skyscraper_right, banner_select('wide_skyscraper',(@skyscraper_right ? @skyscraper_right.id : '')), :class => 'short_field') %>
  </div>
</div>
<div class='clear'></div>
<div class="actions">
  <%= submit_tag "Set Ads", :disable_with => 'Saving...', :class => 'lg_button' %>
</div>

</form>