config/routes.rb
Champax::Application.routes.draw do

  namespace :admin do
    root :to => 'coupons#index'
    resources :businesses
    resources :categories 
    resources :coupons
    resources :settings, :only => [:index]
    match '/settings/set_ads', :to => 'settings#set_ads', :as => :settings_set_ads
    resources :ads
    resources :sessions, :only => [:new, :create, :destroy]
    resources :admin_user, :only => [:edit, :update]
    
    match '/login', :to => 'sessions#new'
    match '/logout', :to => 'sessions#destroy'
  end
  
  match "/c/:id/" => 'views#tweet_link'
  match "/New-Coupons" => 'views#by_new', :as => :coupons_by_new 
  match "/Hot-Coupons" => 'views#by_hot', :as => :coupons_by_hot 
  match "/Online-Only-Coupons" => 'views#by_online_only', :as => :coupons_by_online_only
  match "/Search-Coupons" => 'views#search'
  match "/Contact" => 'pages#contact', :as => :contact
  match "/Help" => 'pages#help', :as => :help
  match "/Help/Disable-Popups" => 'pages#help_popups', :as => :help_popup
  match "/About" => 'pages#about', :as => :about
  match "/For-Businesses" => 'pages#for_businesses', :as => :for_businesses 
  match "/For-Businesses/Why-Coupons" => 'pages#why_coupons', :as => :why_coupons 
  match "/print/:id" => 'views#print_coupon'
  match "/ajax/rate_coupon/:id", :to => "views#rate_coupon", :as => :rate_coupon
  match "/:name/c" => 'views#by_category'
  match "/:name/t" => 'views#by_town'
  match "/:name/d" => 'views#by_distance'
  match "/:business_name/:short_description/:id" => 'views#coupon', :constraints => { :short_description => /.*/ }
  
  
  root :to => 'pages#home'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  attr_accessible :business_id, :category_id, :short_description, :long_description, :valid_from, :valid_until, :image, :categories_attributes, :value, :featured, :online_only
  has_attached_file :image, :storage => :s3, :s3_credentials => "#{RAILS_ROOT}/config/s3.yml", :path => "coupon/:id/:attachment/:style.:extension", :styles => { :page => '640x', :print => '1200x' }
  
  belongs_to :business
  belongs_to :category
  
  acts_as_mappable :through => :business
  
  validates :business_id, :presence => true
  validates :short_description, :presence => true, :length => { :maximum => 250 } 
  validates :valid_from, :presence => true
  validates :valid_until, :presence => true
  validates :value, :numericality => true
  
  scope :active, where('valid_until >= ? AND valid_from <= ?', Date.today, Date.today)
  scope :expired, where('valid_until < ?', Date.today)
  
  def print 
    self.prints.nil? ? self.prints = 1 : self.prints += 1 
    self.save
    Savings.first().add_to(value)        
  end  
  
  def rate(val)
    self.rating.nil? ? self.rating = val : self.rating = ((self.total_ratings*self.rating)+val)/(self.total_ratings+1)
    self.total_ratings.nil? ? self.total_ratings = 1 : self.total_ratings += 1
    self.save
  end
  
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::BaseController
  before_filter :authenticate
  
  def index
    @filter = params[:filter] 
    @filter ||= 'active'
    if @filter == 'active' 
      @coupons = Coupon.active.includes(:business).order('businesses.name, coupons.created_at').paginate(:page => params[:page])
    elsif @filter == 'expired'
      @coupons = Coupon.expired.includes(:business).order('businesses.name, coupons.created_at').paginate(:page => params[:page])
    else 
      @coupons = Coupon.includes(:business).order('businesses.name, coupons.created_at').paginate(:page => params[:page])
    end
    @title = "Coupons"
  end
  
  def new
    @coupon = Coupon.new()
    set_selects
    if @business = Business.find_by_id(params[:business])
      @coupon.business = @business
    end
    @title = "Add Coupon" 
  end
  
  def create 
    @coupon = Coupon.new(params[:coupon])
    if @coupon.save
      if params[:tweet_this] 
        client = Twitter::Base.new(:consumer_key => CONFIG['twitter']['consumer_key'], :consumer_secret => CONFIG['twitter']['consumer_secret'], :access_key => CONFIG['twitter']['access_key'], :access_secret => CONFIG['twitter']['access_secret'] )
        begin
          client.update(tweet_worthy("New Coupon for #{@coupon.business.name} - #{@coupon.short_description}")+" http://#{request.host_with_port}/c/#{@coupon.id}")
        rescue
          flash[:error] = "Could Not Make Tweet."         
        end
      end
      flash[:success] = "Coupon created."
      redirect_to admin_coupons_path
    else
      set_selects
      @title = "Add Coupon"
      render 'new'
    end
  end
  
  def edit
    @coupon = Coupon.find(params[:id])
    set_selects
    @title = "Edit Coupon" 
  end
  
  def update
    @coupon = Coupon.find(params[:id])
  	if @coupon.update_attributes(params[:coupon])
  		flash[:success] = "Coupon updated."
  		redirect_to admin_coupons_path
  	else
  	  set_selects
  		@title = "Edit Coupon"
  		render 'edit'
  	end
  end
  
  def destroy
    Coupon.find(params[:id]).destroy
    flash[:success] = "Coupon Deleted"
    redirect_to admin_coupons_path  
  end
  
  private 
  
  def set_selects 
    @businesses_select = Business.order('name').collect { |l| [ l.name, l.id ] }
    @categories_select = Category.order('name').collect { |l| [ l.name, l.id ] }
  end
  
  def tweet_worthy(str)
    if str.size > 100
      str = str[0..99]
    end
    str
  end
  
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/views/admin/coupons/_form.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="subtitle">Connections</div>
<div class="field">
  <%= f.label :business_id, "Business" %>
  <%= select(:coupon, :business_id, @businesses_select) %>
</div>
<div class="field">
  <%= f.label :category_id, "Category" %>
  <%= select(:coupon, :category_id, @categories_select) %>
</div>
<div class="subtitle">Details</div>
<div class="field">
  <%= f.label :short_description %>
  <%= f.text_field :short_description %>
</div>
<div class="field">
  <%= f.label :value, "Estimated Value" %>
  <%= f.text_field :value, :class => 'short_field' %>
</div>
<div class="field">
  <%= f.label :valid_from %>
  <%= date_select :coupon, :valid_from, { :order => [:month,:day,:year] }, :class => 'date_select' %>
</div>
<div class="field">
  <%= f.label :valid_until %>
  <%= date_select :coupon, :valid_until, { :order => [:month,:day,:year] }, :class => 'date_select' %>
</div>
<div class="field">
  <%= f.label :long_description %>
  <%= f.text_area :long_description %>
</div>
<div class="subtitle">Options</div>
<div class="field">
  <%= f.label :featured, :class => 'check_box' %>
  <%= f.check_box :featured, :class => 'check_box' %>
  <%= f.label :online_only, :class => 'check_box' %>
  <%= f.check_box :online_only, :class => 'check_box' %>
</div>
<div class="subtitle">Image</div>
<div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>
<div class="field">
  <label>Current Image</label>
  <% if @coupon.image.exists? %>  
    <%= image_tag @coupon.image.url(:page) %>
  <% else %>
    <div class="not_found">No Image Set</div>
  <% end %>
</div>

app/views/admin/coupons/edit.html.erb
<% content_for :side_menu do %>
  <div id="admin_side_menu">
    <%= button_to 'Delete Coupon', admin_coupon_path(@coupon), :method => :delete, :confirm => "Are you sure you would like to delete this coupon?", :class => 'lg_button' %>
  </div>
<% end %>

<div class="title">Edit Coupon</div>

<%= form_for(@coupon, :url => admin_coupon_path, :html => { :class => 'admin_form', :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div class="actions">
    <%= f.submit "Update", :disable_with => 'Saving...', :class => 'lg_button' %>
  </div>
<% end %>

app/views/admin/coupons/index.html.erb
<% content_for :side_menu do %>
  <div id="admin_side_menu">
    <%= button_to 'Create New Coupon', new_admin_coupon_path, :method => :get, :class => 'lg_button' %>
  </div>
<% end %>


<div class="admin_filter_table">View: <%= link_to 'Active', params.merge(:filter => 'active'), :class => ('bold' if @filter == 'active' )  %> | <%= link_to 'Expired', params.merge(:filter => 'expired'), :class => ('bold' if @filter == 'expired' ) %> | <%= link_to 'All', params.merge(:filter => 'all'), :class => ('bold' if @filter == 'all' ) %> </div>
<div class="title"><%= @title %></div>
<table class="admin_table">
  <tr>
    <th>Business Name</th>
    <th>Short Description</th>
    <th>Valid From</th>
    <th>Valid Until</th> 
  </tr>
  <% @coupons.each do |coupon| %>
    <tr onClick="document.location='<%= edit_admin_coupon_path(coupon) %>'"> 
      <td><%= coupon.business.name %></td>
      <td><%= coupon.short_description %></td>
      <td><%= coupon.valid_from %></td>
      <td><%= coupon.valid_until %></td>
    </tr>
  <% end %>
</table>
  
<div class='admin_paging'><%= will_paginate %></div>

app/views/admin/coupons/new.html.erb
<div class="title">Add Coupon</div>

<%= form_for(@coupon, :url => admin_coupons_path, :html => { :class => 'admin_form', :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div class="actions">
    <%= f.submit "Create", :disable_with => 'Saving...', :class => 'lg_button' %>
    <%= check_box_tag "tweet_this", 1, true %>
    <label>Tweet</label>
  </div>
<% end %>