config/routes.rb
Champax::Application.routes.draw do

  namespace :admin do
    root :to => 'coupons#index'
    resources :businesses
    resources :categories 
    resources :coupons
    resources :settings, :only => [:index]
    match '/settings/set_ads', :to => 'settings#set_ads', :as => :settings_set_ads
    resources :ads
    resources :sessions, :only => [:new, :create, :destroy]
    resources :admin_user, :only => [:edit, :update]
    
    match '/login', :to => 'sessions#new'
    match '/logout', :to => 'sessions#destroy'
  end
  
  match "/c/:id/" => 'views#tweet_link'
  match "/New-Coupons" => 'views#by_new', :as => :coupons_by_new 
  match "/Hot-Coupons" => 'views#by_hot', :as => :coupons_by_hot 
  match "/Online-Only-Coupons" => 'views#by_online_only', :as => :coupons_by_online_only
  match "/Search-Coupons" => 'views#search'
  match "/Contact" => 'pages#contact', :as => :contact
  match "/Help" => 'pages#help', :as => :help
  match "/Help/Disable-Popups" => 'pages#help_popups', :as => :help_popup
  match "/About" => 'pages#about', :as => :about
  match "/For-Businesses" => 'pages#for_businesses', :as => :for_businesses 
  match "/For-Businesses/Why-Coupons" => 'pages#why_coupons', :as => :why_coupons 
  match "/print/:id" => 'views#print_coupon'
  match "/ajax/rate_coupon/:id", :to => "views#rate_coupon", :as => :rate_coupon
  match "/:name/c" => 'views#by_category'
  match "/:name/t" => 'views#by_town'
  match "/:name/d" => 'views#by_distance'
  match "/:business_name/:short_description/:id" => 'views#coupon', :constraints => { :short_description => /.*/ }
  
  
  root :to => 'pages#home'

end

app/views/layouts/_admin_header_addl.html.erb
<div id="admin_header_title">Administration</div>
<div id="admin_header_links">
  <ul>
    <li><%= link_to 'Main Site', root_path %></li>
    <li><%= link_to 'Change Password', edit_admin_admin_user_path(current_admin_user) %></li>
    <li><%= link_to 'Logout', admin_logout_path  %></li>  
  </ul>
</div>

app/views/layouts/_admin_header_menu.html.erb
<div id="header_menu">
<ul>
  <li><%= link_to menu_item('coupons'), admin_coupons_path %></li>
  <li><%= link_to menu_item('businesses'), admin_businesses_path %></li>
  <li><%= link_to menu_item('categories'), admin_categories_path %></li>
  <li><%= link_to menu_item('settings'), admin_settings_path %></li>
</ul>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="clear">
 &copy <%= Date.current.year %> Champak.net. All Rights Reserved.  
</div>

app/views/layouts/_header_addl.html.erb
<div id="header_links">
<ul>
		<li><%= link_to 'Help', help_path %></li>
		<li><%= link_to 'About', about_path %></li>
		<li><%= link_to 'Contact Us', contact_path %></li>
	</ul>
</div>
<div id="header_search">
	Search the site<br />
	<input type="button" value="Search" class="search_button sm_button" id="search_button" />
	<input type="text" class="search_text" name="search" id="search" />
</div>
<div id="header_saved">
	<div class="saved_title">Total Saved:</div><div class="saved_dollar"> $ </div>
	<div id="header_saved_numbers">
	  <% total_savings.value.to_i.to_s.rjust(7,"0").split(//).each do |e| %>
	    <%= image_tag("counter_#{e}.png", { :size=>'24x33', :alt => "0" }) %>
	  <% end %>
  </div>
</div>

app/views/layouts/_header_logos.html.erb
<div id="header_logo"><%= image_tag "logo.png", :alt => 'Champax Logo', :size => "225x155" %></div>
<div id="header_title"><%= image_tag "title.png", :alt => 'Champax', :size => "229x65" %></div>

app/views/layouts/_header_menu.html.erb
<div id="header_menu">
	<ul>
  	<li><%= link_to menu_item("home"), root_path %></li>
    <li><%= link_to menu_item("new_coupons"), coupons_by_new_path %></li>
    <li><%= link_to menu_item("hot_coupons"), coupons_by_hot_path %></li>
    <li><%= link_to menu_item("online_only"), coupons_by_online_only_path %></li>
    <li><%= link_to menu_item("for_businesses"), for_businesses_path %></li>
	</ul>
</div>

app/views/layouts/_metadata.html.erb
<meta name="description" content="<%= @meta_description ? "#{@meta_description} Champak.net, the Best Local Coupons and the Best Deals. " : "Printable Coupons Available Online for Your Favorite Local Businesses at Champak.net, Your Direct Mail Leader for Vermont, New York, and New Hampshire"  %>">
<meta name="keywords" content="<%= "#{@meta_keywords}, " if @meta_keywords %>Coupons, Vermont Coupons, New York Coupons, Burlington Coupons, Burlington Shopping, Burlington Deals, Discounts, Deals, Local Deals, Local Discounts, Vermont Discounts, Vermont Deals, Burlington VT, Champak, Champak.net">

app/views/layouts/_side_hot.html.erb
<div id="side_hot">
  <%= image_tag 'hot_coupons_side.png', :alt => 'Hot Coupons', :size => '255x27' %>
  <% side_hot_coupons.each do |coupon| %>
    <div class='side_hot_coupon'>
      <div class='side_hot_actions'>
        <div class="addthis_default_style addthis_toolbox">
          <a class="addthis_button_facebook" addthis:url="<%= base_url+coupon_link(coupon) %>"></a><a class="addthis_button_twitter" addthis:url="<%= base_url+coupon_link(coupon) %>" addthis:title="Check Out this Coupon for <%= coupon.business.name %>" ></a>
        </div>
      </div>   
      <div class='business_name'><%= link_to coupon.business.name, coupon_link(coupon) %></div>
      <div class='description'><%= link_to coupon.short_description, coupon_link(coupon) %></div>
    </div>
  <% end %>
</div>

app/views/layouts/_side_menu.html.erb
<div id="side_menu">
	<div id="side_menu_content">
    <div class="side_menu_field">
    	View Coupons by Category:<br/>
      <%= select_by_category %>
    </div>
    <div class="side_menu_field">
    	View Coupons by Town:<br/>
      <%= select_by_town %>
    </div>
    <div class="side_menu_field">
    	View Coupons by Distance:<br/>
      <input type="text" class="zipcode" id="select_zip" name="select_zip" value="Enter ZIP Code" />
      <input type="button" class="sm_button" id="select_zip_find" value="Find" />
    </div>
  </div>
	<div id="side_menu_bottom"></div>
</div>

app/views/layouts/_skyscraper_ads.html.erb
<% skyscraper_left = Ad.find_by_id(Setting::getSetting('skyscraper_left'))
   skyscraper_right = Ad.find_by_id(Setting::getSetting('skyscraper_right')) %>

<% if skyscraper_left && !skyscraper_left.image.url.empty? %>
  <div id="skyscraper_left" class="skyscraper">
    <%= link_to image_tag(skyscraper_left.image.url, :size => '160x600'), skyscraper_left.url, :target => '_blank' %>
  </div>
<% end %>
<% if skyscraper_right && !skyscraper_right.image.url.empty? %>
  <div id="skyscraper_right" class="skyscraper">
    <%= link_to image_tag(skyscraper_right.image.url, :size => '160x600'), skyscraper_right.url, :target => '_blank' %>
  </div>
<% end %>
<% if skyscraper_left || skyscraper_right %>
  <div class="skyscraper_clear"></div>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'all' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'jquery.rating', :media => 'all' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><%= admin_title %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="robots" content="noindex, nofollow">
  <%= csrf_meta_tag %>  
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
<div id="container">
<div id="header">
  <%= render 'layouts/header_logos' %>
  <%= render 'layouts/admin_header_addl' %> 
  <%= render 'layouts/admin_header_menu' %> 
</div>
<div id="header_separator"></div>

<div id="admin_body">
<div id="admin_right_bar">
  <%= yield :side_menu %>
</div>

<div id="content">
  <% flash.each do |key, value| %>
  	<div class="flash <%= key %>"><%= value %></div>
  <% end %> 

<%= yield %>

</div>
<div class="clear"></div>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><%= admin_title %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="robots" content="noindex, nofollow">
  <%= csrf_meta_tag %>  
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
<div id="small_container">
<div id="header">
  <%= render 'layouts/header_logos' %>
</div>
<div id="small_content">
  <% flash.each do |key, value| %>
  	<div class="flash <%= key %>"><%= value %></div>
  <% end %> 

<%= yield %>

</div>
<div id="small_content_bottom"></div>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><%= @title %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="robots" content="noindex">
  <%= javascript_include_tag :defaults %>
  <%= render 'layouts/stylesheets' %>
</head>
<script language="javascript">
$(function() {
    window.focus();
    window.print();
    if (navigator.userAgent.toLowerCase().indexOf('chrome') == -1) {
      window.close();
    }
  });
</script>
<body >
<%= yield %>
</body>
</html>